#!/usr/bin/env python3
"""Generate blueprint/src/content.tex from items.json and dependency data.

If LeanArchitect JSON output exists in .lake/build/blueprint/module/,
automatically adds \\lean{} and \\leanok annotations to formalizable items.
Run `lake build :blueprint` (or extract_blueprint --all) first to generate
the JSON data.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def load_json(path):
    with open(path) as f:
        return json.load(f)

def load_lean_architect_data():
    """Load LeanArchitect JSON output and build a mapping from module name
    (e.g. 'Definition1_2') to a list of {name, sorry_free} dicts."""
    blueprint_dir = ROOT / ".lake" / "build" / "blueprint" / "module" / "SutherlandNumberTheoryLecture1" / "Chapter1"
    if not blueprint_dir.exists():
        return {}
    result = {}
    for jf in sorted(blueprint_dir.glob("*.json")):
        module = jf.stem  # e.g. "Definition1_2"
        data = json.load(open(jf))
        decls = []
        for item in data:
            if item["type"] == "node":
                d = item["data"]
                decls.append({
                    "name": d["name"],
                    "sorry_free": d["hasLean"],
                })
        result[module] = decls
    return result

def item_id_to_module(item_id):
    """Map an item ID like 'Lecture1/Definition1.2' to a module name like 'Definition1_2'."""
    # Extract the part after the last /
    part = item_id.split("/")[-1]
    # Replace dots with underscores: "Definition1.2" -> "Definition1_2"
    return part.replace(".", "_")

def sanitize_label(item_id):
    """Convert item ID to a valid LaTeX label."""
    # e.g. "Lecture1/Definition1.2" -> "Lecture1:Definition1.2"
    return item_id.replace("/", ":")

def escape_latex(text):
    """Escape special LaTeX characters in text."""
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text

def item_type_to_env(item_type):
    """Map item type to LaTeX environment name."""
    env_map = {
        "theorem": "theorem",
        "proposition": "proposition",
        "lemma": "lemma",
        "corollary": "corollary",
        "definition": "definition",
        "example": "example",
        "remark": "remark",
        "introduction": "remark",
        "discussion": "remark",
        "bibliography": "remark",
    }
    return env_map.get(item_type, "remark")

def is_formalizable(item_type):
    """Check if an item type is formalizable (needs Lean declaration)."""
    return item_type in {"theorem", "proposition", "lemma", "corollary",
                         "definition", "example"}

def main():
    items = load_json(ROOT / "items.json")
    internal_deps = load_json(ROOT / "dependencies" / "internal.json")
    external_deps = load_json(ROOT / "dependencies" / "external.json")
    lean_data = load_lean_architect_data()

    if lean_data:
        print(f"Found LeanArchitect data for {len(lean_data)} modules")
    else:
        print("No LeanArchitect data found (run `lake build :blueprint` or extract_blueprint --all first)")

    # Build reverse map: item_id -> list of external dep IDs that it uses
    ext_used_by = {}  # ext_id -> list of item_ids
    for ext in external_deps:
        for item_id in ext.get("used_by", []):
            if item_id not in ext_used_by:
                ext_used_by[item_id] = []
            ext_used_by[item_id].append(ext["id"])

    lines = []
    lines.append("% Auto-generated by scripts/generate_blueprint.py")
    lines.append("% Do not edit manually.")
    lines.append("")

    # Chapter for external dependencies
    lines.append(r"\chapter{External Dependencies}")
    lines.append("")
    for ext in external_deps:
        ext_label = sanitize_label(ext["id"])
        title = escape_latex(ext["description"])
        category = ext.get("category", "unknown")
        lines.append(r"\begin{definition}[%s]" % title)
        lines.append(r"\label{%s}" % ext_label)
        lines.append(r"\leanok")
        lines.append(r"Category: %s." % escape_latex(category))
        lines.append(r"\end{definition}")
        lines.append("")

    # Chapter for lecture content
    lines.append(r"\chapter{Lecture 1}")
    lines.append("")

    formalized_count = 0
    for item in items:
        item_id = item["id"]
        item_type = item["type"]
        title = escape_latex(item["title"])
        label = sanitize_label(item_id)
        env = item_type_to_env(item_type)

        lines.append(r"\begin{%s}[%s]" % (env, title))
        lines.append(r"\label{%s}" % label)

        # Collect all dependencies: internal + external
        deps = []

        # Internal dependencies
        int_dep_ids = internal_deps.get(item_id, [])
        for dep_id in int_dep_ids:
            deps.append(sanitize_label(dep_id))

        # External dependencies
        ext_dep_ids = ext_used_by.get(item_id, [])
        for ext_id in ext_dep_ids:
            deps.append(sanitize_label(ext_id))

        if deps:
            lines.append(r"\uses{%s}" % ", ".join(deps))

        # Add \lean{} and \leanok from LeanArchitect data
        if is_formalizable(item_type):
            module = item_id_to_module(item_id)
            decls = lean_data.get(module, [])
            if decls:
                decl_names = ", ".join(d["name"] for d in decls)
                lines.append(r"\lean{%s}" % decl_names)
                if all(d["sorry_free"] for d in decls):
                    lines.append(r"\leanok")
                    formalized_count += 1
        else:
            lines.append(r"\discussion{%s}" % label)

        lines.append(r"[%s: %s]" % (item_type.capitalize(), title))

        lines.append(r"\end{%s}" % env)
        lines.append("")

    content = "\n".join(lines)

    out_path = ROOT / "blueprint" / "src" / "content.tex"
    out_path.write_text(content)
    total_formalizable = sum(1 for i in items if is_formalizable(i["type"]))
    print(f"Wrote {out_path} ({len(items)} items + {len(external_deps)} external deps)")
    print(f"Formalization status: {formalized_count}/{total_formalizable} items linked to sorry-free Lean code")

if __name__ == "__main__":
    main()
